/*****************************************************************************
 * Project: RooFit                                                           *
 *                                                                           *
  * This code was autogenerated by RooClassFactory                            * 
 *****************************************************************************/

#ifndef ROORELBW
#define ROORELBW

#include "RooAbsPdf.h"
#include "RooRealProxy.h"
#include "RooCategoryProxy.h"
#include "RooAbsReal.h"
#include "RooAbsCategory.h"
 
class RooRelBW : public RooAbsPdf {
public:
  RooRelBW() {} ; 
  RooRelBW(const char *name, const char *title,
	      RooAbsReal& _x,
	      RooAbsReal& _mass,
	      RooAbsReal& _width);
  RooRelBW(const RooRelBW& other, const char* name=0) ;
  virtual TObject* clone(const char* newname) const { return new RooRelBW(*this,newname); }
  inline virtual ~RooRelBW() { }

protected:

  RooRealProxy x ;
  RooRealProxy mass ;
  RooRealProxy width ;
  
  Double_t evaluate() const ;

private:

  ClassDef(RooRelBW,1) // Your description goes here...
};
 
#endif
