/*********************************************************************************************************
  Macro to launch analysis plugin for phi analysis
  Created by fbellini@cern.ch, 12/11/2017

Usage: 
- Modify the main settings (see description below) 
  IMPORTANT: the plugin needs you to configure the global variables,
  please DON'T SKIP THIS PASSAGE!!!
- Launch with AliRoot
  $ aliroot -l -b -q -x RunGridRsnTrain.C"(<mode>, <Grid User>, <suffix>, <ROOT>, <ALIROOT>, <ALIPHYSICS>)"

  <mode> can be "test", "full" or "terminate" - MANDATORY
  <Grid User> is your grid username - MANDATORY
  <suffix> is an additional string which identifies the names of the executables and jdl - OPTIONAL
           if it is empty (e.g., "") all files created by the plugin will have the same name 
  <ROOT>, <ALIROOT>, <ALIPHYSICS> must be compatible versions of the packages (check on Monalisa)
**********************************************************************************************************/

#if !defined (__CINT__) || defined (__CLING__)
#include "AliAnalysisAlien.h"
#include "AliAnalysisManager.h"
#include "AliESDInputHandler.h"
#include "AliMCEventHandler.h"
#include "AliVEventHandler.h"
#include "AliAODInputHandler.h"
#include "AliTaskCDBconnect.h"
#include "AliPhysicsSelectionTask.h"
#include "AliMultSelectionTask.h"
#endif

TChain * CreateESDChain(TString esdpath=".",Int_t ifirst=-1,Int_t ilast=-1);
void     RunGridRsnTrain(TString pluginmode="test", Short_t ntest = 1, TString suffix="Xe",
			 TString dataset = "LHC17n", Bool_t isMC = 0, Bool_t isPP = 0, Int_t aodN = -1,
			 TString username="fbellini", TString aliPhysicsVer = "vAN-20170926-1");

void RunGridRsnTrain(TString pluginmode, Short_t ntest, TString suffix,
		     TString dataset, Bool_t isMC, Bool_t isPP, Int_t aodN,
		     TString username, TString aliPhysicsVer)
{

  //------------------------------------------------------------------------------------
  //--------------------------------- LIBRARIES ---------------------------------------
  //-----------------------------------------------------------------------------------    

#if !defined (CINT) || defined (CLING)
  gInterpreter->ProcessLine(".include $ROOTSYS/include");
  gInterpreter->ProcessLine(".include $ALICE_ROOT/include");
  gInterpreter->ProcessLine(".include $ALICE_PHYSICS/include");
#else
  gROOT->ProcessLine(".include $ROOTSYS/include");
  gROOT->ProcessLine(".include $ALICE_ROOT/include");
  gROOT->ProcessLine(".include $ALICE_PHYSICS/include");
#endif
  
  printf("%s\n",gSystem->GetIncludePath());
  
  // Pythia libraries
  gSystem->Load("liblhapdf");
  gSystem->Load("libEGPythia6");
  gSystem->Load("libpythia6");
  gSystem->Load("libAliPythia6");
  
  //------------------------------------------------------------------------------------
  //--------------------------------- DATASETS, RUNLIST --------------------------------
  //------------------------------------------------------------------------------------     
  Int_t yearMC;
  Int_t yearData;
  TString sim = "";
  TString data = "";
  Int_t ppass = 0;
  Int_t * runList;
  Int_t runNmin = 0;
  Int_t runNmax = 1;
  
  // ESD/AOD analysis
  Bool_t isESD = ((aodN<0)? 1 : 0);
  
  //pp 5 TeV 2015 sample
  Int_t LHC15n[27] = {244340, 244343, 244351, 244355, 244359, 244364, 244377, 244411, 244416, 244418,
		      244421, 244453, 244456, 244480, 244481, 244482, 244483, 244484, 244531, 244540,
		      244542, 244617, 244618, 244619, 244626, 244627, 244628};
  
  if (dataset.Contains("15n")) {
    runList = LHC15n;
    data = "LHC15n";
    ppass = 4;
    sim =  "LHC17d8";
    yearData = 2015;
    yearMC = 2017;
  }
  
  //Xe-Xe 5.44 TeV 2017 sample
  Int_t LHC17n[2] = {280234, 280235};
      
  if (dataset.Contains("17n")) {
    runList = LHC17n;
    data = "LHC17n";
    ppass = 1;
    sim =  "LHC17j7";
    yearData = 2017;
    yearMC = 2017;
  }
  
  //------------------------------------------------------------------------------------
  //--------------------------------- DATASET and PATHS -------------------------------
  //------------------------------------------------------------------------------------ 
  /* Define data path */
  TString myGridDataDir="/alice";
  TString myDataPattern="";
  
  /* Define output directory and names of the files generated by the plugin.
     Omit the extension of the files, it will be automatically set by the SetupIO function */
  TString myOutDir  = "phi";
  TString myWorkDir = "RsnOut";
  TString myJDLname = "jobPhi";
  TString myExecutableName = "RunPhi";
  TString myMacroName = "RunPhi";
  
  //Setup I/O paths and file names
  if (isMC) myGridDataDir.Append(Form("/%i/%s",yearMC, sim.Data()));
  else myGridDataDir.Append(Form("/data/%i/%s",yearData, data.Data()));
  
  if (isESD) {
    if (isMC) myDataPattern="*AliESDs.root";
    else myDataPattern=Form("/pass%i/*AliESDs.root",ppass);
  } else {
    if (aodN>0) myDataPattern=Form("AOD%03i/*AliAOD.root",aodN);
    else myDataPattern="AOD/*AliAOD.root";
    if (!isMC) myDataPattern.Prepend(Form("*/pass%i/",ppass)); 
  }
  
  myJDLname.Append(suffix.Data()); myJDLname.Append(".jdl");
  myExecutableName.Append(suffix.Data()); myExecutableName.Append(".sh");
  myMacroName.Append(suffix.Data()); myMacroName.Append(".C");
  
  if (myOutDir.IsNull()) myOutDir = Form("%s_pass%i_%s", (isMC ? sim.Data() : data.Data()), ppass, suffix.Data());
  
  Printf("=========================================  Setup I/O:");
  Printf("myGridDataDir = %s", myGridDataDir.Data());
  Printf("myDataPattern = %s", myDataPattern.Data());
  Printf("myWorkDir = %s", myWorkDir.Data());
  Printf("myOutDir = %s", myOutDir.Data());
  Printf("myJDLname = %s", myJDLname.Data());
  Printf("myExecutableName = %s", myExecutableName.Data());
  Printf("myMacroName = %s", myMacroName.Data());
  Printf("=======================================================");

  //------------------------------------------------------------------------------------
  //--------------------------------- ANALYSIS MODE ------------------------------------
  //------------------------------------------------------------------------------------ 
  /* Set the usage of the alien plugin to kTRUE to run the analysis on grid or in test mode,
     set it to kFALSE to run test locally.
     If you want to run merging via plugin, disable the local merge when running in "full" mode or "terminate" mode (multiple merging stages are possible).
     Enable the local merge at the last step of the "terminate" to download locally the final merged output.
     Otherwise, local merge is always possible. */
  TString analysisMode  = "grid"; //in alternative: "local"
  Bool_t useAlienPlugin = (pluginmode.IsNull()? kFALSE : kTRUE);
  Bool_t isLocalMerge = 0;
  
  if(analysisMode=="grid") {
    if (!useAlienPlugin) analysisMode = "local";
    TGrid::Connect("alien://");
  }
  
  //needed for running locally
  //The file added to the chain can also be a file on the grid, e.g. alien://<full path on grid>/AliESDs.root
  Long64_t nentries=100000;
  Long64_t firstentry=0; //needed to read input when running locally
  TChain *chain = 0x0;
  AliAnalysisAlien *plugin = 0x0; 
  
  //-----------------------------------------------------------------------------------
  //--------------------------------- ALIEN PLUGIN ------------------------------------
  //----------------------------------------------------------------------------------- 

  if(useAlienPlugin) {
    
    plugin = new AliAnalysisAlien();
    plugin->SetRunMode(pluginmode.Data());
    plugin->SetUser(username.Data());
    plugin->SetAPIVersion("V1.1x");
    plugin->SetAliPhysicsVersion(aliPhysicsVer.Data()); 
    plugin->SetGridWorkingDir(myWorkDir.Data()); 
    plugin->SetGridOutputDir(myOutDir.Data()); 
    plugin->SetCheckCopy(kTRUE);
    plugin->SetGridDataDir(myGridDataDir.Data());
    plugin->SetDataPattern(myDataPattern.Data());
    if (!isMC) plugin->SetRunPrefix("000");
    
    for (Int_t irun=runNmin;irun<runNmax;irun++){
      plugin->AddRunNumber((Int_t )runList[irun]);
    }
    
    //change this to se the number of files to be used in "test" mode
    plugin->SetNtestFiles(ntest); 
    
    // change this not to have the output run-by-run 
    plugin->SetNrunsPerMaster(1);
    plugin->SetOutputToRunNo(1); 
    
    // feel free to modify the list of include paths and libraries according to your need!
    plugin->AddIncludePath("-I. -I$ROOTSYS/include -I$ALICE_ROOT/include -I$ALICE_PHYSICS/include -I$ALICE_PHYSICS/OADB/ -I$ALICE_PHYSICS/OADB/COMMON -I$ALICE_PHYSICS/OADB/COMMON/MULTIPLICITY -g");
    //Order matters!!!!
    plugin->SetAdditionalLibs("liblhapdf.so libEGPythia6.so libpythia6.so libAliPythia6.so");
  
    // these have to be customized 
    plugin->SetAnalysisMacro(myMacroName.Data()); 
    plugin->SetExecutable(myExecutableName.Data()); 
    plugin->SetJDLName(myJDLname);
  
    // more job option 
    plugin->SetDefaultOutputs(kTRUE);
    plugin->SetExecutableCommand("root -b -q");
    plugin->SetMaxInitFailed(15);
    plugin->SetMasterResubmitThreshold(10);
    plugin->SetTTL(50000);
    plugin->SetInputFormat("xml-single");
    plugin->SetSplitMaxInputFileNumber(30);
    plugin->SetSplitMode("se");
  
    // Set properly the global flac to enable/disable local or plugin merging  
    plugin->SetMergeViaJDL(!isLocalMerge);
  
    // Force a single merging stage or define multiple stages     
    // plugin->SetOneStageMerging(kTRUE);                          
    plugin->SetMaxMergeStages(2); // adapt n to your expected number of files              
    
  } else {

    //run locally over a file chain
    if (isESD){
      chain=new TChain("esdTree");
      chain->Add("AliESDs.root");  
    } else {
      chain=new TChain("aodTree");
      chain->Add("AliAOD.root"); 
    }
    if (chain) Printf("Input chain has %d entries\n",(Int_t)chain->GetEntries());

  }
  
  //------------------------------------------------------------------------------------
  //--------------------------------- ANALYSIS SETTINGS --------------------------------
  //------------------------------------------------------------------------------------    
  /* Settings for the train  */
  Bool_t enaMultSel = kTRUE;
  Bool_t runMonOnly = kFALSE;
  Bool_t enableMon = kTRUE;
  
  /* settings for event mixing */
  Int_t nmix = 5; 
  
  //------------------------------------------------------------------------------------
  //--------------------------------- CONFIGURE TRAIN ----------------------------------
  //------------------------------------------------------------------------------------ 
  
  AliAnalysisManager *mgr = new AliAnalysisManager("RsnAnalysisManager");
  mgr->SetCommonFileName("RsnOut.root");
  TString out = "";
  if (isESD) {
    out = "esdTree";
    ::Info("RunGridRsnTrain", "Creating ESD handler");
    AliESDInputHandler *esdHandler = new AliESDInputHandler();
    mgr->SetInputEventHandler(esdHandler);
    esdHandler->SetNeedField(); //needed to load magnetic field configuration
    
    if (isMC) {
      ::Info("RunGridRsnTrain", "Creating MC handler");
      AliMCEventHandler *mcHandler = new AliMCEventHandler();
      mcHandler->SetReadTR(kFALSE);
      mgr->SetMCtruthEventHandler(mcHandler);
    }
  } else {
    out = "aodTree";
    ::Info("RunGridRsnTrain", "Creating AOD handler");
    AliAODInputHandler *aodHandler = new AliAODInputHandler();
    mgr->SetInputEventHandler(aodHandler);
  }
  
    // compile the class and load the add task macro
    // here we have to differentiate between using the just-in-time compiler
    // from root6, or the interpreter of root5


#if !defined (CINT) || defined (CLING)
  
  // AliTaskCDBconnect * taskCDB = reinterpret_cast<AliTaskCDBconnect*>(gInterpreter->ExecuteMacro("$ALICE_PHYSICS/PWGPP/PilotTrain/AddTaskCDBconnect.C(\"raw://\")"));
  // if (!taskCDB) return;
  AliPhysicsSelectionTask * physSelTask = 0x0;
  AliMultSelectionTask * taskMult = 0X0;
  AliAnalysisTaskPIDResponse * pidTask = 0x0;
  AliAnalysisTask * pidQAtask = 0x0;
  AliRsnMiniAnalysisTask * rsnAnaTask = 0x0;
  
  if (isMC) {
    //Physics selection
    physSelTask = reinterpret_cast<AliPhysicsSelectionTask*>(gInterpreter->ExecuteMacro("$ALICE_PHYSICS/OADB/macros/AddTaskPhysicsSelection.C(kTRUE, kFALSE)"));
    
    //Multiplicity selection
    taskMult = reinterpret_cast<AliMultSelectionTask*>(gInterpreter->ExecuteMacro("$ALICE_PHYSICS/OADB/COMMON/MULTIPLICITY/macros/AddTaskMultSelection.C()"));//kTRUE, "B") 
    taskMult->SetSelectedTriggerClass(AliVEvent::kINT7);
    taskMult->SetUseDefaultMCCalib(isMC);

    //PID response
    pidTask = reinterpret_cast<AliAnalysisTaskPIDResponse*>(gInterpreter->ExecuteMacro("$ALICE_ROOT/ANALYSIS/macros/AddTaskPIDResponse.C(kTRUE, kTRUE, kTRUE)"));
    if (enableMon) pidQAtask = reinterpret_cast<AliAnalysisTask*>(gInterpreter->ExecuteMacro("$(ALICE_ROOT)/ANALYSIS/macros/AddTaskPIDqa.C"));

    //Resonance task
    rsnAnaTask = reinterpret_cast<AliRsnMiniAnalysisTask*>(gInterpreter->ExecuteMacro("$HOME/alice/resonances/RsnAnaRun2/phiXeXe/AddTaskPhiXeXe.C(kTRUE)"));

  } else {
    //Physics selection
    physSelTask = reinterpret_cast<AliPhysicsSelectionTask*>(gInterpreter->ExecuteMacro("$ALICE_PHYSICS/OADB/macros/AddTaskPhysicsSelection.C(kFALSE, kTRUE)"));
    physSelTask->SelectCollisionCandidates(AliVEvent::kINT7);

    //Multiplicity selection
    taskMult = reinterpret_cast<AliMultSelectionTask*>(gInterpreter->ExecuteMacro("$ALICE_PHYSICS/OADB/COMMON/MULTIPLICITY/macros/AddTaskMultSelection.C()"));//kTRUE, "B") 
    taskMult->SetSelectedTriggerClass(AliVEvent::kINT7);

    //PID response
    pidTask = reinterpret_cast<AliAnalysisTaskPIDResponse*>(gInterpreter->ExecuteMacro("$ALICE_ROOT/ANALYSIS/macros/AddTaskPIDResponse.C(kFALSE)"));
    if (enableMon) pidQAtask = reinterpret_cast<AliAnalysisTask*>(gInterpreter->ExecuteMacro("$(ALICE_ROOT)/ANALYSIS/macros/AddTaskPIDqa.C"));

    //Resonance task
    rsnAnaTask = reinterpret_cast<AliRsnMiniAnalysisTask*>(gInterpreter->ExecuteMacro("$HOME/alice/resonances/RsnAnaRun2/phiXeXe/AddTaskPhiXeXe.C(kFALSE)"));
  }

#else

  // === CDB connection =======================================================
  // Check that the correct trigger class is selected!!! USER DEFINED!!! 
  gROOT->LoadMacro("$ALICE_PHYSICS/PWGPP/PilotTrain/AddTaskCDBconnect.C");
  AliTaskCDBconnect *taskCDB = AddTaskCDBconnect("raw://");
  if (!taskCDB) return;
  
  // === PHYSICS SELECTION ====================================================
  // Check that the correct trigger class is selected!!! USER DEFINED!!!
  gROOT->LoadMacro("$ALICE_PHYSICS/OADB/macros/AddTaskPhysicsSelection.C");
  AliPhysicsSelectionTask* physSelTask = AddTaskPhysicsSelection(isMC);
  
  //add also info on physics selection statistics in separate file
  AliAnalysisDataContainer *cstatsout = (AliAnalysisDataContainer*)mgr->GetOutputs()->FindObject("cstatsout");
  cstatsout->SetFileName("EventStatPhysSel.root");
  
  // === CENTRALITY/MULTIPLICITY ==============================================
  //Use MultSelectionTask to provide centrlaity estimate
  gROOT->LoadMacro("$ALICE_PHYSICS/OADB/COMMON/MULTIPLICITY/macros/AddTaskMultSelection.C");
  AliMultSelectionTask* taskMult = 0X0;
  if (enaMultSel) {
    taskMult = (AliMultSelectionTask *) AddTaskMultSelection(); //kTRUE, "B") to run in calibration mode
    if (isMC) taskMult->SetUseDefaultMCCalib(isMC);
  }
  
  // === PID RESPONSE =========================================================
  // Set PIDresponse task   
  gROOT->LoadMacro("$ALICE_ROOT/ANALYSIS/macros/AddTaskPIDResponse.C");
  AliAnalysisTask * pidRespTask = AddTaskPIDResponse(isMC, isMC, isMC);  //isMC, autoEsd, tuneOnData

  // === PID QA ================================================================
  // Enable PIDqa - standard configuration  
  gROOT->LoadMacro("$(ALICE_ROOT)/ANALYSIS/macros/AddTaskPIDqa.C ");
  AliAnalysisTask* pidQAtask = 0x0;
  if (enableMon) AddTaskPIDqa();
   
  // === RSN TASKS =============================================================
  // Add resonance tasks
  gROOT->LoadMacro("$ALICE_PHYSICS/PWGLF/RESONANCES/macros/mini/qa/AddTaskRsnQA.C ");
  AliRsnMiniAnalysisTask * rsnQaTask = AddTaskRsnQA(isMC, kFALSE, "V0M", AliVEvent::kINT7, "phi", 1, 0);
  
  // gROOT->LoadMacro("$ALICE_PHYSICS/PWGLF/RESONANCES/macros/mini/AddTaskPhiXeXe.C");
  gROOT->LoadMacro("$HOME/alice/resonances/RsnAnaRun2/phiXeXe/AddTaskPhiXeXe.C");
  AliRsnMiniAnalysisTask * rsnAnaTask = AddTaskPhiXeXe(isMC);
  
 
#endif
  
  ::Info("AnalysisSetup", "<<<<<<<<<<<<<<<<< TRAIN CONFIGURATION >>>>>>>>>>>>>>>>");
  if (physSelTask) ::Info("AnalysisSetup", "Added physics selection");
  //  if (cstatsout)   ::Info("AnalysisSetup", "Saving Physics Selection output in file EventStatPhysSel.root");
  if (taskMult)    ::Info("AnalysisSetup", "Add centrality/multiplicity computation tasks");
  if (pidTask) ::Info("AnalysisSetup", "Added task for PID response");
  if (pidQAtask)   ::Info("AnalysisSetup", "Added task for PID QA");
  if (rsnAnaTask)  ::Info("AnalysisSetup", "Added task for Rsn Analysis");
  ::Info("AnalysisSetup", "Setup successful");

  if (out.Length() < 1) return;
  
  // add plugin to analysis manager
  if (useAlienPlugin)
    mgr->SetGridHandler(plugin);
  
  // init analysis
  if(!mgr->InitAnalysis()) {
    printf("Error: Analysis manager failed to be initialized. Nothing done!\n");
    return;
  }
  mgr->PrintStatus();
  
  //start analysis
  mgr->StartAnalysis(analysisMode.Data(),chain,nentries,firstentry);  
  return;
}
 
 

/***************************************************************************************************/
TChain *CreateESDChain(TString esdpath, Int_t ifirst, Int_t ilast)
{
  TChain *chainESD = new TChain("esdTree");

  if(ifirst<0) {
    chainESD->Add("AliESDs.root");
  } else {
    for(Int_t i=ifirst; i<=ilast; i++) {
      TString esdfile=esdpath; esdfile+=i; esdfile.Append("/AliESDs.root");
      chainESD->Add(esdfile.Data());
    }
  }
  
  return chainESD;
}
